title: Keybindings Documentation
theme: just-the-docs
url: "https://yourusername.github.io/keybinds"
baseurl: "/keybinds"
repository: yourusername/keybinds

search_enabled: true
search:
  heading_level: 2
  previews: 3
  max_results: 25

last_edit_date_format: "%A, %B %e %Y at %l:%M %p"

footer_content: "Documentation built with <a href=\"https://pmarsceill.github.io/just-the-docs/\" target=\"_blank\">Just the Docs</a>"

color_scheme: light

aux_links:
  "GitHub Repo":
    - "https://github.com/yourusername/keybinds"
