# Site Settings
title: Keybindings Documentation
repository: intisy/keybinds
url: "https://intisy.github.io/keybinds"
baseurl: "/keybinds"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Defaults for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"

# Sidebar navigation
# To use this navigation, add the following to your page's front matter:
# sidebar:
#   nav: "docs"
#
# Or to use the main navigation, simply omit the sidebar front matter.
# See: https://mmistakes.github.io/minimal-mistakes/docs/navigation/
docs_nav:
  - title: "GNOME"
    url: /docs/gnome/
  - title: "IntelliJ"
    url: /docs/intellij/
  - title: "Nautilus"
    url: /docs/nautilus/
  - title: "Vim"
    url: /docs/vim/
