site_name: Keybindings Documentation
site_url: https://intisy.github.io/keybinds/
repo_url: https://github.com/intisy/keybinds
repo_name: intisy/keybinds

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Operating Systems:
      - Windows: windows.md
      - macOS: macos.md
  - Linux:
      - Desktop Environments:
          - GNOME: gnome.md
          - KDE Plasma: kde.md
          - XFCE: xfce.md
      - File Managers:
          - Nautilus: nautilus.md
  - Development Tools:
      - VS Code: vscode.md
      - IntelliJ: intellij.md
      - Vim: vim.md
      - Git: git.md
      - Docker: docker.md
